export let vendors = [
    "hiromu.designs",
    'basedkawaii',
    'Furescentm ',
    'fur_Smith',
    'Weeb Culture',
    'mdotrage',
    'u.k.o fitness',
    'Chibizilla',
    'Buki Pins',
    'Low Standards Designs ',
    '_Crisisculture',
    'Bishoujucomplex',
    'Secrettsumori',
    'Xpresskins',
    'FreshTango',
    'V1Tech',
    'Senpai Squad',
    'Tenga',
    'iymagic',
    '@nekomimipunks',
    'WNTD @wntdinc',
    'Otakuruma',
    '_Shinobu.us',
    'Himawarii.US',
    'kurozoku',
    'catchmydrift.jp',
    'angy frog art',
    'Bimyou Workshop',
    'Kusoya.jp',
    "The Kigu Stop / Whats Clackin",
    'Pikadude',
    'AnimeCoast',
    'Send Calamity',
    'Dreamscape.cc',
    'ara.culture',
    'BloodArtisan',
    'Mangahole'
]

export let artistAlley = [

    'ZRStudio',
    'Carlos Arts',
    'nightdigital',
    'Yarn Bubbles',
    'hadokoa.contrast',
    'Lethal Bliss',
    'Iridescent manga',
    'Lexxie Lynn',
    'Starberri Kai',
    'Hyperbooster',
    'Mikela Kim',
    'Livinglegacyshop',
    'mestizamakes',
    'zzyzzyyart',
    'Cute and Deadly',
    'Story Teller Cosplayy',
    'Deviousdrawing',
    'YamiWave',
    'mtsugarr',
    'theimaginaryking',
    'Crafty Hedonest',
    'DentelleElysee',
    'Golden Koi Designs',
    'EckoEckos',
    'Heartwerm',
    'Die Sentai',
    'scribble squab',
    'Cyanidecady',
    'Soul Tooth',
    'Sakimi Chan',
    'nichiyoubi.art',
    'x3dustco',

]