export let vendors = [
    "hiromu.designs",
    'basedkawaii',
    'Furescentm ',
    'fur_Smith',
    'Weeb Culture',
    'mdotrage',
    'u.k.o fitness',
    'Chibizilla',
    'Buki Pins',
    'Low Standards Designs ',
    '_Crisisculture',
    'Bishoujucomplex',
    'Secrettsumori',
    'Xpresskins',
    'FreshTango',
    'V1Tech',
    'Senpai Squad',
    'Tenga',
    'iymagic',
    '@nekomimipunks',
    'WNTD @wntdinc',
    'Otakuruma',
    '_Shinobu.us',
    'Sushitoclothing',
    'Himawarii.US',
    'kurozoku',
    'catchmydrift.jp',
    'angy frog art',
    'Bimyou Workshop',
    'Kusoya.jp',
    "The Kigu Stop / Whats Clackin",
    'Pikadude',
    'AnimeCoast',
    'Send Calamity',
    'Dreamscape.cc',
    'ara.culture',
    'BloodArtisan',
    'Mangahole'
]